# -*- coding: utf-8 -*-
"""loan default.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SthzFWhTbEtMI1QJ1afsdiscyTsqhA28
"""

!pip install faker plotly scikit-learn -q

import pandas as pd
import numpy as np
import random
from faker import Faker

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

fake = Faker()

loan_statuses = ['Fully Paid', 'Default']
home_ownerships = ['Rent', 'Own', 'Mortgage']
purposes = ['Education', 'Business', 'Car', 'Medical', 'Personal']
grades = ['A', 'B', 'C', 'D']

data = []

for i in range(1000):

    annual_inc = random.randint(20000, 150000)
    loan_amnt = random.randint(1000, 50000)
    int_rate = round(random.uniform(5, 25), 2)

    term = random.choice([36, 60])

    emp_length = random.randint(1, 20)

    home = random.choice(home_ownerships)
    purpose = random.choice(purposes)
    grade = random.choice(grades)

    status = random.choice(loan_statuses)

    data.append([
        loan_amnt,
        term,
        int_rate,
        annual_inc,
        emp_length,
        home,
        purpose,
        grade,
        status
    ])

df = pd.DataFrame(data, columns=[
    'loan_amnt',
    'term',
    'int_rate',
    'annual_inc',
    'emp_length',
    'home_ownership',
    'purpose',
    'grade',
    'loan_status'
])

df.head()

print(df.isnull().sum())

df.drop_duplicates(inplace=True)

df.info()

print("Average Loan Amount:", df['loan_amnt'].mean())

print("Average Income:", df['annual_inc'].mean())
plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x='loan_status'
)

plt.title("Loan Status Distribution")
plt.show()
print("Maximum Loan:", df['loan_amnt'].max())

print("Minimum Loan:", df['loan_amnt'].min())

plt.figure(figsize=(10,5))

sns.histplot(
    df['loan_amnt'],
    bins=30,
    kde=True
)

plt.title("Loan Amount Distribution")
plt.show()

plt.figure(figsize=(10,5))

sns.histplot(
    df['annual_inc'],
    bins=30,
    kde=True
)

plt.title("Annual Income Distribution")
plt.show()

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df,
    x='annual_inc',
    y='loan_amnt',
    hue='loan_status'
)

plt.title("Income vs Loan Amount")
plt.show()

fig = px.bar(
    df,
    x='purpose',
    color='loan_status',
    title='Loan Purpose Analysis'
)

fig.show()

fig = px.bar(
    df,
    x='home_ownership',
    color='loan_status',
    title='Home Ownership vs Loan Status'
)

fig.show()

plt.figure(figsize=(10,5))

sns.boxplot(
    data=df,
    x='loan_status',
    y='int_rate'
)

plt.title("Interest Rate vs Loan Status")
plt.show()

def risk_level(rate):

    if rate < 10:
        return "Low Risk"

    elif rate < 18:
        return "Medium Risk"

    else:
        return "High Risk"

df['Risk_Level'] = df['int_rate'].apply(risk_level)

df[['int_rate','Risk_Level']].head()

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x='Risk_Level'
)

plt.title("Risk Level Distribution")
plt.show()

encoded = pd.get_dummies(
    df[['home_ownership','purpose','grade']],
    drop_first=True
)

corr_df = pd.concat([
    df[['loan_amnt','annual_inc','int_rate','emp_length']],
    encoded
], axis=1)

plt.figure(figsize=(14,8))

sns.heatmap(
    corr_df.corr(),
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

X = df[['annual_inc','int_rate','term']]

y = df['loan_amnt']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

print(predictions[:10])

score = r2_score(y_test, predictions)

print("R2 Score:", score)

plt.figure(figsize=(10,6))

plt.scatter(
    y_test,
    predictions
)

plt.xlabel("Actual Loan Amount")
plt.ylabel("Predicted Loan Amount")

plt.title("Actual vs Predicted Loan Amount")

plt.show()

print("Total Records:", len(df))

print("Average Income:",
      round(df['annual_inc'].mean(),2))

print("Average Loan Amount:",
      round(df['loan_amnt'].mean(),2))

print("Average Interest Rate:",
      round(df['int_rate'].mean(),2))

print("Model R2 Score:",
      round(score,4))